apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot1-may7-3-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/chatbot1-may7-3/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/chatbot1-may7-3-gitops.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot1-may7-3
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
