apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot1-may7-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot1-may7-3
  name: chatbot1-may7-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
